name: Deploy workflow
  on: 
    push:
      branches:
        - main

  env: 
    AZURE_WEBAPP_NAME: 
    AZURE_WEBAPP_PATH:
    NODE_VERSION:
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Node JS
        uses: actions/setup@node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      
      - name: npm install
        run: 
          # install the project
          npm install
        working-directory:

      - name: npm build
        run: 
          # Build the project
          npm run build --if-present
        working-directory:

      - name: npm test
        run: 
          # test the project
          npm run test --if-present
        working-directory:

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}


    
